# Challenge 2
## Data cleansing
Before to load the data to python, it was necessary clean data set. For this purpose the set of songs that belong to music genders different to _Jazz & Blues_ or _Soul and Reaggae_ were deleted. The string attributes also were deleted. After, the representation of classes was changed, it was selected "0" to representate the class _Jazz & Blues_ and "1" to representate the class Soul and Reagge.

The cleaned data was load to python with the following code:

In [1]:
#numpy to read data
import numpy as np
# We use sklearn to split the data
from sklearn.model_selection import train_test_split
# We use the confusion matrix to evaluate the model
from sklearn.metrics import confusion_matrix
# We use aca nmber to evaluate the model
from sklearn.metrics import accuracy_score
# Random for LMS method
import random
# Got mathematics operations
import math

#importar los datos
data = np.genfromtxt('clean_data.csv', delimiter=';')

In [2]:
labels= data[:,0]
features = data[:,1:]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2)

In [4]:
def SGD(features, labels):
    size = len(features[0])
    w0 = np.array([1e-2]*size)
    #tol = 1e-6
    #err = 100
    num = 1e-6

    for i in range(5000000):
        rand_index = random.randint(0,len(labels)-1)
        xi, yi = (features[rand_index],labels[rand_index])
        g = 1 / (1 + math.exp(-np.dot(w0,xi)))
        e = yi - g
        w1 = w0 + num*e*xi
        #err = np.linalg.norm(w1-w0)
        w0 = np.copy(w1)
    #print(w0)
    return w0

In [5]:
w0 = SGD(X_train,y_train)

In [6]:
predictions = []
for x in X_test:
    y = 1 / (1 + math.exp(-np.dot(w0,x)))
    y = 1 if y>=0.5 else 0
    predictions.append(y)
predictions = np.array(predictions)

In [7]:
matrix = confusion_matrix(y_test, predictions) 
ACA1 = accuracy_score(y_test, predictions) 

In [8]:
matrix

array([[642, 219],
       [ 92, 717]], dtype=int64)

In [9]:
ACA1

0.8137724550898203

In [10]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_train, y_train, test_size=0.5)
w0 = SGD(X_train2,y_train2)

In [11]:
predictions = []
for x in X_test:
    y = 1 / (1 + math.exp(-np.dot(w0,x)))
    y = 1 if y>=0.5 else 0
    predictions.append(y)
predictions = np.array(predictions)

In [12]:
matrix = confusion_matrix(y_test, predictions) 
ACA2 = accuracy_score(y_test, predictions) 

In [13]:
matrix

array([[741, 120],
       [184, 625]], dtype=int64)

In [14]:
ACA2

0.8179640718562874

In [15]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X_train, y_train, test_size=0.8)
w0 = SGD(X_train3,y_train3)

In [16]:
predictions = []
for x in X_test:
    y = 1 / (1 + math.exp(-np.dot(w0,x)))
    y = 1 if y>=0.5 else 0
    predictions.append(y)
predictions = np.array(predictions)

In [17]:
matrix = confusion_matrix(y_test, predictions) 
ACA3 = accuracy_score(y_test, predictions) 

In [18]:
matrix

array([[597, 264],
       [ 78, 731]], dtype=int64)

In [19]:
ACA3

0.7952095808383234

In [20]:
X_train4, X_test4, y_train4, y_test4 = train_test_split(X_train, y_train, test_size=0.9)
w0 = SGD(X_train4,y_train4)

In [21]:
predictions = []
for x in X_test:
    y = 1 / (1 + math.exp(-np.dot(w0,x)))
    y = 1 if y>=0.5 else 0
    predictions.append(y)
predictions = np.array(predictions)

In [22]:
matrix = confusion_matrix(y_test, predictions) 
ACA4 = accuracy_score(y_test, predictions) 

In [23]:
matrix

array([[470, 391],
       [ 37, 772]], dtype=int64)

In [24]:
ACA4

0.7437125748502994

In [25]:
print(ACA1,ACA2,ACA3,ACA4)

0.8137724550898203 0.8179640718562874 0.7952095808383234 0.7437125748502994
