# Challenge 2
## Dependencies
To run this code is necessary numpy and sklearn libraries.
## Description
The objective of this challenge is classify data in two classes: _Jazz & Blues_ and _Soul and Reaggae_ using a logistic regresión.
## Data cleansing
Before to load the data to python, it was necessary clean data set. For this purpose the set of songs that belong to music genders different to _Jazz & Blues_ or _Soul and Reaggae_ were deleted. The string attributes also were deleted. After, the representation of classes was changed, it was selected "0" to representate the class _Jazz & Blues_ and "1" to representate the class Soul and Reagge.

The cleaned data was load to python with the following code:

In [1]:
#numpy to read data
import numpy as np
# We use sklearn to split the data
from sklearn.model_selection import train_test_split
# We use the confusion matrix to evaluate the model
from sklearn.metrics import confusion_matrix
# We use aca nmber to evaluate the model
from sklearn.metrics import accuracy_score
# Random for LMS method
import random
# Got mathematics operations
import math

#importar los datos
data = np.genfromtxt('clean_data.csv', delimiter=';')

After, it is separate the class of the features

In [2]:
labels= data[:,0]
features = data[:,1:]

### Part one: Train the algorithm using all data


In [3]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2)

We use SGD algorithm to find the parameters of logistical regresión, the definition of the method is the following. To select the learning rate I variate manually this parameter, I noticed that in a big values of this parameter the method began to diverge, so I iterate and at the end i noticed that the bigger number that the algortithm toletare was 1e-6.

In [4]:
def SGD(features, labels):
    size = len(features[0])
    w0 = np.array([1e-2]*size)
    num = 1e-6
    for i in range(1000000):
        rand_index = random.randint(0,len(labels)-1)
        xi, yi = (features[rand_index],labels[rand_index])
        g = 1 / (1 + math.exp(-np.dot(w0,xi)))
        e = yi - g
        w1 = w0 + num*e*xi
        #err = np.linalg.norm(w1-w0)
        w0 = np.copy(w1)
    #print(w0)
    return w0

We call the algorithm with the correct parameters:

In [5]:
w0 = SGD(X_train,y_train)

To evaluate the algorithm, I did predictios with test set

In [6]:
predictions = []
for x in X_test:
    y = 1 / (1 + math.exp(-np.dot(w0,x)))
    y = 1 if y>=0.5 else 0
    predictions.append(y)
predictions = np.array(predictions)

To evaluate the results we will use the confusion matrix (CM) and the accuracy score (ACA). In the columns of CM representate the actual class 0 and the predicted class 1, the rows representate the predicted data class
<table>
  <tr>
    <th colspan="2" rowspan="2"></th>
    <th colspan="2">Actual class<br></th>
  </tr>
  <tr>
    <td>0</td>
    <td>1</td>
  </tr>
  <tr>
    <td rowspan="2"><br>Predicted</td>
    <td>0<br></td>
    <td><span style="color:rgb(51, 51, 51)">TP</span></td>
    <td>FP<br></td>
  </tr>
  <tr>
    <td>1</td>
    <td>FN</td>
    <td>TN</td>
  </tr>
</table>
The ACA number is defined as following equation and its representate the average of data that was predicted in the correct class divided the number of records predicted for this class for each class.
$ACA= \frac{1}{2}\frac{TP}{TP+FP}+\frac{1}{2}\frac{TN}{FN+TN}$


In [7]:
matrix1 = confusion_matrix(y_test, predictions) 
ACA1 = accuracy_score(y_test, predictions) 
print('Confusion matriz')
print(matrix1)
print('Accuracy number')
print(ACA1)

Confusion matriz
[[828  24]
 [449 369]]
Accuracy number
0.7167664670658682


### Part two: Train the algorithm using 50% of data


In [8]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_train, y_train, test_size=0.5)
w0 = SGD(X_train2,y_train2)

In [9]:
predictions = []
for x in X_test:
    y = 1 / (1 + math.exp(-np.dot(w0,x)))
    y = 1 if y>=0.5 else 0
    predictions.append(y)
predictions = np.array(predictions)

In [10]:
matrix2 = confusion_matrix(y_test, predictions) 
ACA2 = accuracy_score(y_test, predictions)
print('Confusion matrix')
print(matrix2)
print('Accuracy number')
print(ACA2)

Confusion matrix
[[552 300]
 [ 43 775]]
Accuracy number
0.7946107784431138


### Part three: Train the algorithm using 20% of data


In [11]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X_train, y_train, test_size=0.8)
w0 = SGD(X_train3,y_train3)

In [12]:
predictions = []
for x in X_test:
    y = 1 / (1 + math.exp(-np.dot(w0,x)))
    y = 1 if y>=0.5 else 0
    predictions.append(y)
predictions = np.array(predictions)

In [13]:
matrix3 = confusion_matrix(y_test, predictions) 
ACA3 = accuracy_score(y_test, predictions)
print('Confusion matrix')
print(matrix3)
print('Accuracy number')
print(ACA3)

Confusion matrix
[[453 399]
 [ 23 795]]
Accuracy number
0.7473053892215569


### Part four: Train the algorithm using 10% of data


In [14]:
X_train4, X_test4, y_train4, y_test4 = train_test_split(X_train, y_train, test_size=0.9)
w0 = SGD(X_train4,y_train4)

In [15]:
predictions = []
for x in X_test:
    y = 1 / (1 + math.exp(-np.dot(w0,x)))
    y = 1 if y>=0.5 else 0
    predictions.append(y)
predictions = np.array(predictions)

In [16]:
matrix4 = confusion_matrix(y_test, predictions) 
ACA4 = accuracy_score(y_test, predictions)
print('Confusion matrix')
print(matrix4)
print('Accuracy number')
print(ACA4)

Confusion matrix
[[619 233]
 [ 82 736]]
Accuracy number
0.811377245508982


## Results

In [17]:
print(ACA1,ACA2,ACA3,ACA4)

0.7167664670658682 0.7946107784431138 0.7473053892215569 0.811377245508982


The difference between the accuracy of the models is significally diferent. In this challenge, we can note a big differences when the training set is reduced, this implies that SKLearn library has a more complex model with a better accuracy. Nevertheless, even SDG is not a fine model, with the enough among of data we can obtain a close accuracy to SKLearn model. In terms cost and benefits SDG algorithm give as a good model in a reasonable time.

#### Valerie Parra Cortés
201619703