# Challenge 1
## Data cleansing
Before to load the data to python, it was necessary clean data set. For this purpose the set of songs that belong to music genders different to _Jazz & Blues_ or _Soul and Reaggae_ were deleted. The string attributes also were deleted. After, the representation of classes was changed, it was selected "0" to representate the class _Jazz & Blues_ and "1" to representate the class Soul and Reagge.

The cleaned data was load to python with the following code:

In [1]:
#Import nunpy to read data
import numpy as np
# SKLearn is used to make the logistic regression
from sklearn.linear_model import LogisticRegression
# In order to split randomply train_test_split method (of SKLearn) will be user
from sklearn.model_selection import train_test_split
# To evalue the results a confusión matrix and ACA were used
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
#Import data
data = np.genfromtxt('clean_data.csv', delimiter=';')


It is necessary separate the class of the features on the clase:

In [2]:
labels= data[:,0]
features = data[:,1:]

### Part one: Train the algorithm using all data
This challenge is divided in four parts. In the first part all the data will be used. To separte the training data of test data the train_test_split was used:

In [3]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2)

With the training set, we can create the logistic regression. The solver parameter was fixed in newton-cg in order to facilitate the convergence

In [4]:
clf = LogisticRegression(solver = "sag", max_iter=100000).fit(X_train, y_train)

With the model created we can predict the new classes with the test set

In [5]:
predictions = clf.predict(X_test)

To evaluate the results we will use the confusion matrix (CM) and the accuracy score (ACA). In the columns of CM representate the actual class 0 and the predicted class 1, the rows representate the predicted data class
<table>
  <tr>
    <th colspan="2" rowspan="2"></th>
    <th colspan="2">Actual class<br></th>
  </tr>
  <tr>
    <td>0</td>
    <td>1</td>
  </tr>
  <tr>
    <td rowspan="2"><br>Predicted</td>
    <td>0<br></td>
    <td><span style="color:rgb(51, 51, 51)">TP</span></td>
    <td>FP<br></td>
  </tr>
  <tr>
    <td>1</td>
    <td>FN</td>
    <td>TN</td>
  </tr>
</table>
The ACA number is defined as
$ACA= \frac{TP}{TP+FP}+\frac{TN}{FN+TN}=0.83$

This means that our model have 83% pf hits.

In [6]:
matrix = confusion_matrix(y_test, predictions) 
ACA = accuracy_score(y_test, predictions) 
print(matrix)
print(ACA)

[[716 164]
 [125 665]]
0.8269461077844311


### Part two: Train the algorithm using 50% of data
In this part we will use only de half of data to training and test the data

In [7]:
# With the half-data we separate the set again into training and test sets.
X2_train, X2_test, y2_train, y2_test = train_test_split(X_train, y_train, test_size=0.5)

In [8]:
clf2 = LogisticRegression(solver = "sag", max_iter=100000).fit(X2_train, y2_train)

In [9]:
predictions2 = clf2.predict(X_test)

In [10]:
matrix2 = confusion_matrix(y_test, predictions2) 
ACA2 = accuracy_score(y_test, predictions2) 
print(matrix2)
print(ACA2)

[[704 176]
 [120 670]]
0.822754491017964


### Part three: Train the algorithm using 20% of data
In this part we will use only the 20% of data to training and test the data

In [11]:
# With the half-data we separate the set again into training and test sets.
X3_train, X3_test, y3_train, y3_test = train_test_split(X_train, y_train, test_size=0.8)

In [12]:
clf3 = LogisticRegression(solver = "sag", max_iter=100000).fit(X3_train, y3_train)

In [13]:
predictions3 = clf3.predict(X_test)

In [14]:
matrix3 = confusion_matrix(y_test, predictions3) 
ACA3 = accuracy_score(y_test, predictions3) 
print(matrix3)
print(ACA3)

[[704 176]
 [139 651]]
0.811377245508982


### Part four: Train the algorithm using 10% of data
In this part we will use only the 10% of data to training and test the data

In [15]:
# With the half-data we separate the set again into training and test sets.
X4_train, X4_test, y4_train, y4_test = train_test_split(X_train, y_train, test_size=0.9)

In [16]:
clf4 = LogisticRegression(solver = "sag", max_iter=100000).fit(X4_train, y4_train)

In [17]:
predictions4 = clf4.predict(X_test)

In [18]:
matrix4 = confusion_matrix(y_test, predictions4) 
ACA4 = accuracy_score(y_test, predictions4) 
print(matrix4)
print(ACA4)

[[719 161]
 [157 633]]
0.8095808383233533


### Results

In [19]:
print(ACA,ACA2,ACA3,ACA4)

0.8269461077844311 0.822754491017964 0.811377245508982 0.8095808383233533


The ACA number almost no has variation between models. This facts sugest that or our data is very linear or every class is very grouped, for this reason the accuracy of model is not improved significaly with the among of data, a small set is significant enough.