# Challenge 1
## Dependencies
To run this code is necessary numpy and sklearn libraries.
## Description
The objective of this challenge is classify data in two classes: Jazz & Blues and Soul and Reggae using a logistic regresión.
## Data cleansing
Before loading the data into Python, it was necessary to clean the data set. For this, the set of songs belonging to different musical genres to _Jazz & Blues_ or _Soul and Reaggae_ was eliminated. String attributes were also deleted. Then, the representation of the classes was changed, "0" was selected to represent the _Jazz & Blues_ class and "1" to represent the Alma and Reagge class.

In [1]:
#Import nunpy to read data
import numpy as np
# SKLearn is used to make the logistic regression
from sklearn.linear_model import LogisticRegression
# In order to split randomply train_test_split method (of SKLearn) will be user
from sklearn.model_selection import train_test_split
# To evalue the results a confusión matrix and ACA were used
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
#Import data
data = np.genfromtxt('clean_data.csv', delimiter=';')


After, it is separate the class of the features:

In [2]:
labels= data[:,0]
features = data[:,1:]

### Part one: Train the algorithm using all data
This challenge is divided in four parts. In the first part all the data will be used. To separte the training data of test data the train_test_split function of SKLear was used:

In [3]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2)

With the training set, we can create the logistic regression. The solver parameter was fixed in sag in order to facilitate the convergence

In [4]:
clf = LogisticRegression(solver = "sag", max_iter=100000).fit(X_train, y_train)

With the model created we can predict the new classes with the test set

In [5]:
predictions = clf.predict(X_test)

To evaluate the results we will use the confusion matrix (CM) and the accuracy score (ACA). 
<table>
  <tr>
    <th colspan="2" rowspan="2"></th>
    <th colspan="2">Actual class<br></th>
  </tr>
  <tr>
    <td>0</td>
    <td>1</td>
  </tr>
  <tr>
    <td rowspan="2"><br>Predicted</td>
    <td>0<br></td>
    <td><span style="color:rgb(51, 51, 51)">TP</span></td>
    <td>FP<br></td>
  </tr>
  <tr>
    <td>1</td>
    <td>FN</td>
    <td>TN</td>
  </tr>
</table>
The ACA number is defined as following equation and its representation the average of data that was predicted in the correct class divided in  the number of records predicted for this class.

$ACA= \frac{1}{2}\frac{TP}{TP+FP}+\frac{1}{2}\frac{TN}{FN+TN}$



In [6]:
matrix = confusion_matrix(y_test, predictions) 
ACA = accuracy_score(y_test, predictions) 
print(matrix)
print(ACA)

[[733 150]
 [132 655]]
0.8311377245508982


### Part two: Train the algorithm using 50% of data


In [7]:
# With the half-data we separate the set again into training and test sets.
X2_train, X2_test, y2_train, y2_test = train_test_split(X_train, y_train, test_size=0.5)

In [8]:
clf2 = LogisticRegression(solver = "sag", max_iter=100000).fit(X2_train, y2_train)

In [9]:
predictions2 = clf2.predict(X_test)

In [10]:
matrix2 = confusion_matrix(y_test, predictions2) 
ACA2 = accuracy_score(y_test, predictions2) 
print('Confusion matrix 50% of data')
print(matrix2)
print('ACA 50% of data')
print(ACA2)

Confusion matrix 50% of data
[[731 152]
 [132 655]]
ACA 50% of data
0.829940119760479


### Part three: Train the algorithm using 20% of data


In [11]:
# With the half-data we separate the set again into training and test sets.
X3_train, X3_test, y3_train, y3_test = train_test_split(X_train, y_train, test_size=0.8)

In [12]:
clf3 = LogisticRegression(solver = "sag", max_iter=100000).fit(X3_train, y3_train)

In [13]:
predictions3 = clf3.predict(X_test)

In [14]:
matrix3 = confusion_matrix(y_test, predictions3) 
ACA3 = accuracy_score(y_test, predictions3) 
print('Confusion matrix 20% of data')
print(matrix3)
print('ACA 20% of data')
print(ACA3)

Confusion matrix 20% of data
[[735 148]
 [142 645]]
ACA 20% of data
0.8263473053892215


### Part four: Train the algorithm using 10% of data


In [15]:
X4_train, X4_test, y4_train, y4_test = train_test_split(X_train, y_train, test_size=0.9)

In [16]:
clf4 = LogisticRegression(solver = "sag", max_iter=100000).fit(X4_train, y4_train)

In [17]:
predictions4 = clf4.predict(X_test)

In [18]:
matrix4 = confusion_matrix(y_test, predictions4) 
ACA4 = accuracy_score(y_test, predictions4) 
print('Confusion matrix 10% of data')
print(matrix4)
print('ACA 10% of data')
print(ACA4)

Confusion matrix 10% of data
[[706 177]
 [121 666]]
ACA 10% of data
0.8215568862275449


### Results

In [19]:
print('ACA numbers for each model')
print(ACA,ACA2,ACA3,ACA4)

ACA numbers for each model
0.8311377245508982 0.829940119760479 0.8263473053892215 0.8215568862275449


The ACA number almost no has variation between models. This facts sugest that or our data is very linear or every class is very grouped, for this reason the accuracy of model is not improved significaly with the among of data, a small set is significant enough. In general terms the models have a good accuracy and we can say that the objective of the challenge was accomplished.

#### Valerie Parra Cortés
201619703